# numpy part1

In [3]:
import numpy as np
import pandas as pd

### (1)create numpy array
### 1. np.array([1,2,3]) or np.array(range(10))
### 2. np.arange(10)

In [4]:
print(np.array([1,2,3])) #里面是列表
print(np.array(range(10)))
print(np.arange(10))#里面是数值

[1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


### (2)类型
### dtype and astype
### datype用np. 可以找到不同类型
### astype 注意不会改变元数据 必须找个变量接着

In [9]:
a=np.array([1,2,3])
#查看类型
print(a.dtype)
#增加类型
b=np.array([1,2,3],dtype=np.float32)
print(b)
#注意astype不会改变元数据 必须找个变量接
b=b.astype(np.bool8)
print(b)



int32
[1. 2. 3.]
[ True  True  True]


### (3)形状 shape 注意后面没有括号
### 几行几列 两个[]组成2位 1个[] 组成1位
### reshape 改变行与列
### flatten() 数据改为一行 变为1位

In [25]:
a=np.arange(12)
print(a)
print(a.shape)
print('*'*50)
b=np.array([[1,2],[2,3]])
print(b)
print(b.shape)
print('*'*50)
c=np.arange(12)
print(c.reshape((3,4)))
print(c.reshape((2,3,2)))
print('*'*50)
print(c.reshape((1,12)))
print(c.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
**************************************************
[[1 2]
 [2 3]]
(2, 2)
**************************************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
**************************************************
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


### (4)数据读取与广播机制 了解一般都是pandas读取
### np.loadtxt
### 二维情况有连个维度shape中有一个 a shape(a,b) 
###                               b shape(c,d) 只要a c与b d中有一对一致就可以计算

### (5)索引与切片 读取数据
### 读取某一行a[1] 连续行a[1:] 某几行a[[1,3,4]]
### 读取某一列a[:,1] 连续列a[:,2:]     某几列a[:,[1,2,3]]  
### 取某及行某激烈a[2:3,3:4]
### 取某行某列的值 a[[1,2,4],[3,4,3]] 去1行3列 以及2行4列的值,第4行第3列的值

In [31]:
a=np.arange(50).reshape((10,5))
print(a)
print('*'*50)
print('*'*50+'取一行')
print(a[[1]])
print('*'*50+'取多行')
print(a[[1,3,4]])
print('*'*50+'取某几个值')
print(a[[1,3],[3,4]])
print('*'*50+'取某几行某几列')
print(a[2:4,2:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
**************************************************
**************************************************取一行
[[5 6 7 8 9]]
**************************************************取多行
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]
**************************************************取某几个值
[ 8 19]
**************************************************取某几行某几列
[[12 13]
 [17 18]]


### (6)数值修改 课通过重新赋值 a[:,2:4]=0 都改为0
### 小于某值的进行修改 a[a<10]=4
### np.where(阈值条件a<3，0小于3替换，10大雨3替换成10) 注意这个array a放到参数位置
### a.clip（10小于10换位10,18大雨18替换成18）注意这个array a 放到外面


In [33]:
a=np.arange(50).reshape((10,5))
print(a)
print('*'*50+'where 该数值')
print(np.where(a<15,10,18))
print('*'*50+'clip 该数值')
print(a.clip(10,18))



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
**************************************************where 该数值
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]]
**************************************************clip 该数值
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 11 12 13 14]
 [15 16 17 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]]


### (7) nan 与常用统计函数
### a!=a 为true的地方为nan np.isnan(a)为true的地方为nan 
### 或者np.sum(a)结果如果为nan 说明a中有nan
### 统计nan个数 np.count_nonzero(np.isnan(a))因为ture 为1 false为0

### 常用统计函数 sum mean median max min ptp最大与最小值差 std
### np.argmax/argmin(a,axis=0)列最大索引

In [35]:
a=np.arange(50).reshape((10,5))
print(np.sum(a,axis=0))
print(np.std(a,axis=0))

[225 235 245 255 265]
[14.36140662 14.36140662 14.36140662 14.36140662 14.36140662]


### (8)nan的处理
### 取当列中的均值代替

In [38]:
a=np.arange(50).reshape((10,5)).astype(np.float32)
a[2:4:,2:]=np.nan
print(a)
for i in range(a.shape[1]):#遍历列
    temp_col=a[:,i]
    nan_num=np.count_nonzero(temp_col !=temp_col)
    if nan_num !=0:#说明列中有nan
        temp_col_not_nan=temp_col[temp_col==temp_col]#列中部位nan的保留
        temp_col[np.isnan(temp_col)]=temp_col_not_nan.mean()#列中其他部位均值代替nan
print(a)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. nan nan nan]
 [15. 16. nan nan nan]
 [20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44.]
 [45. 46. 47. 48. 49.]]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 27. 28. 29.]
 [15. 16. 27. 28. 29.]
 [20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44.]
 [45. 46. 47. 48. 49.]]


### (9)数组拼接 与交换行列
### np.vstack(a,b) 竖直拼接 
### np.hstack(a,b) 水平拼接
### 交换行列 a[[1,2]]=a[[2,1]]

### (10)多种特殊数组 和 找索引 s
### np.zeros((行，列))
### np.ones((行，列))
### np.eye(几行方阵)
### ###################################################
### np.random+ rand 范围0-1  randn 正态  randint(最小，最大，（行，列）)



In [39]:
import random 
a1=np.array([np.random.rand() for i in range(10)])
print(a1)
np.round(a1,2)

[0.58056421 0.35896944 0.61713616 0.57462912 0.983984   0.90508065
 0.14073639 0.17292676 0.6289455  0.09685923]


array([0.58, 0.36, 0.62, 0.57, 0.98, 0.91, 0.14, 0.17, 0.63, 0.1 ])